service: myslsproject

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: slsUser
  region: region, 'us-east-1'
  environment:
    tableName: ${self:custom.tableName}

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  s3Sync:
    - bucketName: myslsprojectupbucket-7619
      localDir: UploadData

functions:
  getUser:
    handler: Lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
          #private: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myslsprojectupbucket-7619
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
